### ISSUE TITLE
Build failing when trying to configure

### ISSUE THREAD

**Issue by chandrakishorSingh** [FNCS/ns-3.26#1]
I have configured the code using the following command as mentioned in the README of this repository.

```
CFLAGS="-g -O2" CXXFLAGS="-g -O2" ./waf configure --prefix=$FNCS_INSTALL --with-fncs=$FNCS_INSTALL --with-zmq=$FNCS_INSTALL --disable-python
```

And I got the following error.

```
Traceback (most recent call last):
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py", line 312, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 167, in run_commands
    parse_options()
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 140, in parse_options
    Context.create_context('options').execute()
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/home/chandrakishor/ns-3.26-master/wscript", line 144, in options
    opt.load('compiler_c')
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 90, in load
    fun(self)
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/chandrakishor/ns-3.26-master/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
```

**Comment by chandrakishorSingh** [comment]
It seems that after executing the above mentioned configure command, a new file is generated at location `.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py`.

The statement at line 310 of this file is as follows.

```
                raise StopIteration
```

It seems this exception always gets raised as it's not followed by any try-catch block and is the last line of a function. So commenting it seems to be the easiest workaround. Hence, I've edited the line as follows.

```
#                raise StopIteration
```

As I was running short of time, I appiled this workaround to get things done. Although, a better(and preferable) approach would be to analyze why such a file is generated while configuring the repo which seems to contain wrong code.
